server:
  port: 8081
spring:
  application:
    name: ViewModule
  r2dbc:
  sql:
    init:
      mode: always
# AWS Aurora PostgreSQL Configuration
aws:
  rds:
    host: 3ntym563zmsmhmbonlj47iw7ay.dsql.us-east-2.on.aws
    port: 5432
    region: us-east-2  # Replace with your AWS region
    username: FAPPMasterUser  # Your IAM database username
    database: furryArtsyPawsPrint  # Your database name
    connection-timeout: 30

jwt:
  secret: 8ca42f9a3a7a589a02d1f37348ff451f9ec170af9c74c81c68ddda89be52970335df42cded640dbae213dcea117a2b80f11720076bbda3c6880cfd28a59bdf52
  expiration: 900000  # 15 minutes in milliseconds
  refresh-expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.FurryArtyPawPrints.ViewModule.utils.AwsIamAuthUtility: DEBUG
    io.r2dbc.postgresql: DEBUG
