CREATE TABLE IF NOT EXISTS "users" (
       "user_id" INTEGER PRIMARY KEY,
       "user_name" VARCHAR(255) NOT NULL,
       "user_last_name" VARCHAR(255) NOT NULL,
       "user_email" VARCHAR(255) NOT NULL UNIQUE,
       "user_password" VARCHAR(500) NOT NULL,
       "user_location" VARCHAR(255),
       "user_type" VARCHAR(50),
       "user_preferences" TEXT,
       "n_commissions" INTEGER,
       "user_com_date" TIMESTAMP,
       "user_com_message" TEXT,
       "user_com_discount" INTEGER,
       "user_twitter" VARCHAR(500),
       "user_facebook" VARCHAR(500),
       "user_blue_sky" VARCHAR(500),
       "user_patreon" VARCHAR(500),
       "last_login" TIMESTAMP,
       "is_active" BOOLEAN DEFAULT TRUE,
       "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
